export const GET_CONTACTS = 'GET_CONTANTS';
export const DELETE_CONTACTS = 'DELETE_CONTANTS';
export const ADD_CONTACTS = 'ADD_CONTACTS';
export const GET_CONTACT = 'GET_CONTANT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';